services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zoe-pos-system
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
      DB_HOST: "qbl5hgdrdxhxtde3se62tuxk"
      DB_PORT: "3306"
      DB_USER: "mysql"
      DB_PASSWORD: "vince-mysql"
      DB_NAME: "default"
      DATABASE_URL: "mysql://mysql:vince-mysql@qbl5hgdrdxhxtde3se62tuxk:3306/default"
